export const metadata = {
  title: 'Tisela',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>Main Layout</h1>
        {children}
      </body>
    </html>
  )
}
